### ISSUE TITLE
fix: replace download dependency

### ISSUE THREAD

**Issue by erezrokah** [netlify/gh-release-fetch#50]
Related to https://github.com/netlify/cli/issues/2744

It has security vulnerabilities since it depends on an outdated `got`.
Doesn't look like it's going to be fixed soon https://github.com/kevva/download/pull/212

**Comment by erezrokah** [comment]
Since we already have `node-fetch` as a dependency it might be good to find something that relies on it instead of having both `got` and `node-fetch` as a dependency.

**Comment by erezrokah** [comment]
Also related to https://github.com/kevva/download/issues/213 and https://github.com/kevva/download/issues/216

**Comment by XhmikosR** [comment]
This no longer happens. :)
